invite_candidates = ["lidiane", "andre", "leticia"]
print(f"Ola {invite_candidates[0].title()}, você está convidado(a) para meu jantar de aniversário.")
print(f"Ola {invite_candidates[1].title()}, você está convidado(a) para meu jantar de aniversário.")
print(f"Ola {invite_candidates[2].title()}, você está convidado(a) para meu jantar de aniversário.")
remove_candidate = "andre"
invite_candidates.remove(remove_candidate)
print(f"{remove_candidate.title()} não poderá comparacer ao jantar")
invite_candidates.append("ingrid")
print(f"{invite_candidates[-1].title()} você está convidado(a) para meu janta de aniversário no lugar de {remove_candidate.title()}")
print()
print("Surgiram novas vagas para o jantar e algumas pessoas serão adicionadas a nossa mesa.")
invite_candidates.insert(0, "cicera")
invite_candidates.insert(2, "sofia")
invite_candidates.append("alice")
print()
print("Eis a nova chamada de aniversário:")
print(f"Ola {invite_candidates[0].title()}, você está convidado(a) para meu jantar de aniversário.")
print(f"Ola {invite_candidates[1].title()}, você está convidado(a) para meu jantar de aniversário.")
print(f"Ola {invite_candidates[2].title()}, você está convidado(a) para meu jantar de aniversário.")
print(f"Ola {invite_candidates[3].title()}, você está convidado(a) para meu jantar de aniversário.")
print(f"Ola {invite_candidates[4].title()}, você está convidado(a) para meu jantar de aniversário.")
print(f"Ola {invite_candidates[5].title()}, você está convidado(a) para meu jantar de aniversário.")

print("recebemos uma pessima notícia de que as mesas do jantar vão ser canceladas restando apenas duas vagas.")
print(f"É realmente uma pena não ter você presente no jantar  {invite_candidates.pop().title()}")
print(f"É realmente uma pena não ter você presente no jantar  {invite_candidates.pop().title()}")
print(f"É realmente uma pena não ter você presente no jantar  {invite_candidates.pop().title()}")
print(f"É realmente uma pena não ter você presente no jantar  {invite_candidates.pop().title()}")
print()
print(f"Ainda é ótimo contar com sua presença {invite_candidates[0].title()}")
print(f"Ainda é ótimo contar com sua presença {invite_candidates[1].title()}")
del invite_candidates[0]
del invite_candidates[0]
print(invite_candidates)