cities = ["veneza", "sicilia", "roma", "portugal", "irlanda"]
print("\nOriginal: ")
print(cities)
print("\nSorted: ")
print(sorted(cities))
print("\nInverted: ")
print(sorted(cities, reverse=True))
print(cities)
print("\nReverse: ")
cities.reverse()
print(cities)
cities.reverse()
print(cities)
print("\nSorted: ")
cities.sort()
print(cities)
print("\nInverted sort: ")
cities.sort(reverse=True)
print(cities)

